### ISSUE TITLE
Flux solutions sometimes negative

### ISSUE THREAD

**Issue by daniel-zid** [afedynitch/MCEq#10] opened 2019-09-09 13:56 UTC
When I run the example, the flux of mu+ at the largest energies is negative. Even worse, if I request the altitudes array written in the tutorial, I get a negative flux along the whole spectrum.

This is the code. Note that in the tutorial density_profile should be changed to density_model:
`h_grid = np.linspace(0,50*1e3*1e2) # altitudes from 0 to 50 km (in cm)`
`X_grid = mceq.density_model.h2X(h_grid)`
`mceq.solve(int_grid=X_grid)`

This is the flux that I get if I request the 0th index:

`mceq.get_solution('total_mu+', grid_idx=0)`
array([ 4.57459576e-04,  5.02743397e-04,  5.49582855e-04,  5.95169863e-04,
        6.38613522e-04,  6.78561026e-04,  7.12793739e-04,  7.36782300e-04,
        7.47844376e-04,  7.41455574e-04,  7.14455176e-04,  6.65299432e-04,
        5.96440848e-04,  5.12792166e-04,  4.22757977e-04,  3.33605336e-04,
        2.51532688e-04,  1.80794513e-04,  1.24579892e-04,  8.31739184e-05,
        5.44727434e-05,  3.46057235e-05,  2.10213276e-05,  1.24846662e-05,
        7.18446007e-06,  4.03049402e-06,  2.20869733e-06,  1.18718134e-06,
        6.27324552e-07,  3.25958177e-07,  1.66478486e-07,  8.37234132e-08,
        4.12620741e-08,  1.99594481e-08,  9.52963181e-09,  4.49767040e-09,
        2.10222053e-09,  9.73108646e-10,  4.46528974e-10,  2.03327644e-10,
        9.19978230e-11,  4.13622218e-11,  1.84833530e-11,  8.21582231e-12,
        3.63327569e-12,  1.60067015e-12,  7.02360234e-13,  3.06851871e-13,
        1.33623814e-13,  5.79440025e-14,  2.50461654e-14,  1.07892165e-14,
        4.63475635e-15,  1.98420091e-15,  8.46177673e-16,  3.59553738e-16,
        1.52377948e-16,  6.43286392e-17,  2.70517531e-17,  1.13385942e-17,
        4.72258107e-18,  1.95983376e-18,  8.09476414e-19,  3.32748586e-19,
        1.36000244e-19,  5.52496051e-20,  2.23739363e-20,  9.01950109e-21,
        3.62712104e-21,  1.45720899e-21,  5.86506094e-22,  2.36352790e-22,
        9.60180196e-23,  3.94854129e-23,  1.64800154e-23,  6.99844041e-24,
        3.02043365e-24,  1.33210903e-24,  5.97773258e-25,  2.72613145e-25,
        1.26211520e-25,  5.91872519e-26,  2.80506864e-26,  1.34524394e-26,
        6.44529742e-27,  3.10952842e-27,  1.49251976e-27,  7.14499143e-28,
        3.39238960e-28,  1.59703324e-28,  7.43880322e-29,  3.41807243e-29,
        1.56062026e-29,  6.91931694e-30,  3.03512203e-30,  1.29930289e-30,
        5.43624664e-31,  2.21410892e-31,  8.70870125e-32,  3.29539200e-32,
        1.19731320e-32,  4.15316295e-33,  1.34886798e-33,  4.07971639e-34,
        1.14360157e-34,  2.93312210e-35,  6.80219574e-36,  1.35930900e-36,
        2.39257912e-37,  3.63297781e-38,  4.42341537e-39,  4.41315192e-40,
        3.00344460e-41,  1.60052231e-42,  6.98651514e-44,  1.48941055e-45,
        3.73584832e-47,  5.34529419e-49, **-2.70492736e-49, -1.20594862e-50,
       -2.41379347e-51**])

And if I request None:

mceq.get_solution('total_mu+', grid_idx=None)
array([-2.56495585e+09, -2.69386548e+09, -2.79880405e+09, -2.87508539e+09,
       -2.91331248e+09, -2.90475549e+09, -2.86791048e+09, -2.80390590e+09,
       -2.73447752e+09, -2.66848310e+09, -2.60558263e+09, -2.50373637e+09,
       -2.23971598e+09, -1.57175669e+09, -2.34563396e+08,  1.75184855e+09,
        3.68874284e+09,  4.33813339e+09,  3.07788513e+09,  9.68520661e+08,
       -3.10652392e+08, -3.90778212e+08,  7.16295421e+07, -9.73232802e+07,
       -2.72156895e+07, -2.18608858e+07, -1.23167147e+07, -7.20178979e+06,
       -4.12584749e+06, -2.34178124e+06, -1.33139296e+06, -7.68322990e+05,
       -4.55211404e+05, -2.80679539e+05, -1.78007723e+05, -1.09796499e+05,
       -6.38886937e+04, -3.46886098e+04, -1.66507190e+04, -5.36353747e+03,
       -7.56866417e+02, -1.72211110e+02, -4.01425815e+02, -2.37317720e+02,
       -1.41780953e+02, -1.23760357e+02, -9.06370851e+01, -5.37071934e+01,
       -2.90847873e+01, -1.53596642e+01, -8.07278541e+00, -4.28226469e+00,
       -2.28826337e+00, -1.22601155e+00, -6.59392834e-01, -3.56355286e-01,
       -1.93726777e-01, -1.06097918e-01, -5.86095168e-02, -3.27077136e-02,
       -1.84630104e-02, -1.05613513e-02, -6.12542220e-03, -3.60010681e-03,
       -2.14165104e-03, -1.28347867e-03, -7.69073182e-04, -4.54755344e-04,
       -2.60522579e-04, -1.39597122e-04, -6.48361491e-05, -2.20317236e-05,
       -4.91537875e-08,  7.38660340e-06,  5.81371438e-06, -3.40044742e-08,
       -4.05879496e-06, -3.66443720e-06, -2.32976524e-06, -1.47832088e-06,
       -9.35842326e-07, -5.91133686e-07, -3.71347026e-07, -2.31816617e-07,
       -1.43056273e-07, -8.74137246e-08, -5.26550358e-08, -3.11782195e-08,
       -1.80896150e-08, -1.02411722e-08, -5.65218278e-09, -3.04220002e-09,
       -1.59893564e-09, -8.24987227e-10, -4.21354012e-10, -2.13718817e-10,
       -1.07035929e-10, -5.14411380e-11, -2.32468677e-11, -9.66305014e-12,
       -3.18665471e-12, -5.58264561e-13,  1.84453359e-15, -2.82266597e-16,
        1.29466474e-18, -7.09706916e-20,  3.47531059e-22, -1.18054374e-23,
        5.86826086e-26, -1.46094551e-27,  7.24048805e-30, -1.43451217e-31,
        7.03074030e-34, -1.16412070e-35,  5.61872958e-38, -8.03042600e-40,
        3.80826690e-42, -4.80195798e-44,  2.52204553e-44, -3.28376768e-46,
        5.19733650e-47])

Could anyone tell me what I'm doing wrong? Thank you!

**Comment by afedynitch** [comment] 2019-09-11 02:51
Hi,

can you please specify how you run the code?

Your statement is::

    h_grid = np.linspace(0,501e31e2) # altitudes from 0 to 50 km (in cm)

...is not code.

**Comment by daniel-zid** [comment] 2019-09-11 06:24
Hi, it is the github editor that substitutes any text between asterisks with bold letters.

I'm just running the tutorial found on (https://github.com/afedynitch/MCEq/blob/master/docs/tutorial.rst) and after defining the altitudes grid and solving, I request
'mceq.get_solution('total_mu+', grid_idx=0)'

I can send you the notebook I use, but it's just the tutorial with this extra instruction.

**Comment by afedynitch** [comment] 2019-09-25 07:02
Sorry for silence, there were a number of travels and personal circumstances involved. I'm looking into this now

**Comment by afedynitch** [comment] 2019-09-25 10:11
The problem is that the values in the X grid are required to be strictly ascending, or, the values in altitude strictly decreasing. This is because the integration runs from the top down to ground and the points at which you want to know the flux are inserted accordingly in between the steps. I have documented this more clearly in the tutorial. The code will also catch this case.

The negative values you have seen for grid_idx = 0 are coming from numerical oscillations due to the energy loss term. Since the magnitude is very small these negative values are not affecting the result. You should watch out for more severe cases if you're doing something exotic.

    h_grid = np.linspace(50 * 1e3 * 1e2, 0) # altitudes from 50 to 0 km (in cm)
    X_grid = mceq.density_model.h2X(h_grid)
    mceq.solve(int_grid=X_grid)
    
    mceq.get_solution('total_mu+', grid_idx=None)

array([ 4.35397657e-04,  4.79612817e-04,  5.25501285e-04,  5.70304023e-04,
        6.13179756e-04,  6.52789107e-04,  6.86813328e-04,  7.10760094e-04,
        7.21896185e-04,  7.15796538e-04,  6.89402179e-04,  6.41296585e-04,
        5.73998354e-04,  4.92454983e-04,  4.04969640e-04,  3.18695230e-04,
        2.39698764e-04,  1.72054524e-04,  1.18591511e-04,  7.92882634e-05,
        5.20425766e-05,  3.31309409e-05,  2.01949097e-05,  1.20522321e-05,
        6.97951465e-06,  3.94554936e-06,  2.17738374e-06,  1.17475783e-06,
        6.20922414e-07,  3.21576402e-07,  1.63425476e-07,  8.16819063e-08,
        4.01579719e-08,  1.94462336e-08,  9.27982470e-09,  4.36832488e-09,
        2.03252981e-09,  9.35655602e-10,  4.26876781e-10,  1.93026691e-10,
        8.66223285e-11,  3.85832306e-11,  1.70877230e-11,  7.52516360e-12,
        3.29701327e-12,  1.43753607e-12,  6.24303533e-13,  2.70185821e-13,
        1.16574065e-13,  5.01528966e-14,  2.15235114e-14,  9.20940666e-15,
        3.92994400e-15,  1.67447691e-15,  7.11268918e-16,  3.01558361e-16,
        1.27718238e-16,  5.40703139e-17,  2.27953814e-17,  9.61694500e-18,
        4.06207206e-18,  1.71398857e-18,  7.23051988e-19,  3.03630044e-19,
        1.28492733e-19,  5.38924718e-20,  2.28814503e-20,  9.71054112e-21,
        4.09235173e-21,  1.73824744e-21,  7.39563885e-22,  3.17511560e-22,
        1.35454194e-22,  5.83162873e-23,  2.51141831e-23,  1.12713403e-23,
        4.98726064e-24,  2.21996519e-24,  9.98059543e-25,  4.58736760e-25,
        2.09028524e-25,  9.84875570e-26,  4.61623495e-26,  2.18487923e-26,
        1.04095859e-26,  5.07474362e-27,  2.52861761e-27,  1.23291794e-27,
        6.27880861e-28,  3.09719374e-28,  1.54882591e-28,  7.62469815e-29,
        3.69276956e-29,  1.75200207e-29,  8.34930351e-30,  3.69972085e-30,
        1.69156444e-30,  7.16257245e-31,  3.03402982e-31,  1.23334521e-31,
        4.83993044e-32,  1.71497896e-32,  5.87018452e-33,  1.90076222e-33,
        5.64782070e-34,  1.54295066e-34,  3.80493924e-35,  8.36531999e-36,
        1.58664763e-36,  2.50793980e-37,  3.20990287e-38,  3.19841951e-39,
        2.41457033e-40,  1.38924924e-41,  5.43481000e-43,  1.39423971e-44,
        3.18597537e-46,  5.07989959e-48, -2.56190581e-48, -1.09663047e-49,
       -2.29443751e-50])

I'm closing this. Please update to 1.0.5.

**Closed by afedynitch** 2019-09-25 10:11 UTC

**Comment by daniel-zid** [comment] 2019-09-25 12:57
Great! Everything works fine now. Thank you!
