### ISSUE TITLE
Retry on failed downloads

### ISSUE THREAD

**Issue by afedynitch** [afedynitch/MCEq#22] opened 2020-04-29 03:20 UTC
Check if local database matches online version can be opened and if not restart download.
Either compare an MD5 or SHA hash to some value stored in config or ... to check the validity of the file. Or try opening it with hdf, without reading here in [mceq_config.py](https://github.com/afedynitch/MCEq/blob/2403487315498e1ae7654f72743445d752a51470/mceq_config.py#L348).

**Comment by jncots** [comment] 2022-06-23 03:44
The issue is fixed with adding sha256 checksum validation of mceq_db file in b45ef4eb9d3afe67522099d84d6e5e7239473c26.

**Closed** 2022-06-23 10:49 UTC
Labels: bug
